spring:
  application:
    name: products-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: products_user
    password: products_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

server:
  port: 8084


axon:
  axonserver:
    servers: localhost:8124
    context: default
    enabled: true
    connect-timeout: 30000
    client-id: products-service
  event-handling:
    processors:
      orderManagementSagaProcessor:
        mode: TRACKING
        initial-segment-count: 1

  serializer:
    general: jackson
    events: jackson
    messages: jackson

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

logging:
  level:
    io.axoniq.axonserver.connector.impl.HeartbeatMonitor: OFF
    io.axoniq.axonserver.connector: WARN
    org.axonframework: INFO

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres-products:5432/products_db
    username: products_user
    password: products_pass



axon:
  axonserver:
    servers: axon-server:8124
    context: default
    keep-alive-time: 5000
    keep-alive-timeout: 10000
  event-handling:
    processors:
      orderManagementSagaProcessor:
        mode: TRACKING
        initial-segment-count:

logging:
  level:
    io.axoniq.axonserver.connector.impl.HeartbeatMonitor: OFF
    io.axoniq.axonserver.connector: WARN
    org.axonframework: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.axonframework.modelling.saga: DEBUG
    org.axonframework.eventhandling: DEBUG