spring:
  application:
    name: config-server

  config:
    activate:
      on-profile: default

  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          enabled: false
        native:
          search-locations: classpath:/config

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: docker  # ← C’est comme ça qu’on active un document

  cloud:
    config:
      server:
        git:
          enabled: false
        native:
          search-locations: classpath:/config
